### PR TITLE
back to asynchronous code with better error handling

### PR DESCRIPTION
**Pull request by Amoki**

### CODE REVIEW

**Comment by xeolabs** [comment]
It seems that we can't have ````await```` inside a non-asynch function's callback, ie.

Screenshot from 2020-10-21 11-58-26

This could be a problem making this code integrate with other utilities within examples - not quite sure how to resolve this - either to make functions like ````utils.loadJSON```` use promises, or make ````loadGLTFIntoXKTModel```` use a callback.

**Comment by Amoki** [comment]
An async function is a function that always returns a Promise. Meaning we can use it as a Promise and call a .then().
```javascript
loadGLTFIntoModel().then(() => {
})
```

**Comment by Amoki** [comment]
And in your example, you can also do 
```javascript
utils.loadJSON("my_model.gltf", async (json) => {
  await loadGLTFIntoModel();
});
```

**Comment by xeolabs** [comment]
Aha cool. BTW I'd like to remove the ````parsingCtx```` argument from ````getAttachment```` if that's OK with you? Just to keep that parsing context private to ````loadGLTFIntoXKTModel````.

**Comment by Amoki** [comment]
OK!

**Comment by xeolabs** [comment]
Would you be able to fix up the examples pages in ./examples?

examples/XKTModel_load_glTF_Duplex.html
examples/XKTModel_load_glTF_MAP.html
examples/XKTModel_load_glTF_Schependomlaan.html

They just need to be tweaked to use the asynch bits, and need an ````getAttachment```` callback.

**Pull request merged**
